language: minimal
matrix:
  include:
    - os: osx
    - os: linux
      services: docker
before_install:
  - bash .travis/before_install_$TRAVIS_OS_NAME.sh
script:
  - bash .travis/script_$TRAVIS_OS_NAME.sh
deploy:
  provider: releases
  api_key:
    secure: LHxcdsW2E+3Dm1FXnIbeKf2yQtEHPP9l4d6j+uK47DmFVDe+u6IpphdiTdrJipiOUrU6eC+lyY3izzh0ej1yklMue99YBbT4KbdtQzHqyeb6KBYs4M/LrB8AU4n8i7O7ZcUCQVtbx5q/be7OtJnwEIJTFSfPnuaJpL3/9mYQ2wU=
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    repo: skaji/relocatable-perl
    all_branches: true
    tags: true
