name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64-linux
          path: x86_64-linux
  darwin-2level:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sw_vers
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-2level
          path: darwin-2level
