name: release

on:
  push:
    tags:
      - '*'

jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64-linux
          path: x86_64-linux
  darwin-2level:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sw_vers
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-2level
          path: darwin-2level
  release:
    runs-on: ubuntu-latest
    needs:
      - x86_64-linux
      - darwin-2level
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: x86_64-linux
          path: x86_64-linux
      - uses: actions/download-artifact@v2
        with:
          name: darwin-2level
          path: darwin-2level
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: x86_64-linux/perl-x86_64-linux.tar.gz
          asset_name: perl-x86_64-linux.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: x86_64-linux/perl-x86_64-linux.tar.xz
          asset_name: perl-x86_64-linux.tar.xz
          asset_content_type: application/x-xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: darwin-2level/perl-darwin-2level.tar.gz
          asset_name: perl-darwin-2level.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: darwin-2level/perl-darwin-2level.tar.xz
          asset_name: perl-darwin-2level.tar.xz
          asset_content_type: application/x-xz
